project:
  type: website

website:
  title: "Helloworldblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ainsleyyoshizumi
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



